# Generated by Django 4.1.7 on 2023-04-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='content',
            new_name='re_content',
        ),
    ]
