# Generated by Django 4.2 on 2023-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dueday',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
