# Generated by Django 4.2 on 2023-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_dueday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueday',
            field=models.DateField(),
        ),
    ]
